before_install:
  - yes | sudo add-apt-repository ppa:hansjorg/rust
  - sudo apt-get update
install:
  - sudo apt-get install rust-nightly nasm
script:
  - sed -i 's/i386-elf-ld/ld/' Makefile
  - make
